### ISSUE TITLE
hidden form fields get rendered

### ISSUE THREAD

**Issue by professor-monkfish** [komola/Bootstrap-Zend-Framework#1]
It's pretty easy to get around this problem with:

$this->addElement('hidden', 'id', array(
            'decorators' => array(
                'ViewHelper'
            ),
            'required'      => true
        ));

but seeing as you're already doing a bunch of work in addElement() could you make hidden form elements really hidden :)

Love this lib :) you da man

**Comment by sebastianhoitz** [comment]
Thanks for your report! I just fixed this issue in the last commit.
