### ISSUE TITLE
Zend_Element_Form_Captcha

### ISSUE THREAD

**Issue by apipemc** [komola/Bootstrap-Zend-Framework#14]
Zend_Element_Form_Captcha make an input text of more, and visible style

Example:

http://s3.subirimagenes.com:81/imagen/previo/thump_7702977sin-ttulo.png

<a href='http://www.subirimagenes.com/imagen-sinttulo-7702977.html'><img src='http://s3.subirimagenes.com:81/imagen/previo/thump_7702977sin-ttulo.png' alt='subir imagenes' border='0'></a>

**Comment by ravidhu** [comment]
i have this issue too :/ any workaround ?

**Comment by ravidhu** [comment]
this issue is solved ! https://github.com/ravid87/Bootstrap-Zend-Framework
