### ISSUE TITLE
submit buttons look weird

### ISSUE THREAD

**Issue by professor-monkfish** [komola/Bootstrap-Zend-Framework#2]
The latest twitter bootstrap renders the submit buttons like this:

&lt;div class="actions"&gt;
            &lt;input class="btn primary" value="Save changes" type="submit"&gt;&amp;nbsp;&lt;button type="reset" class="btn"&gt;Cancel&lt;/button&gt;
          &lt;/div&gt;

Your library doesn't have the div in it.

**Comment by professor-monkfish** [comment]
I added this into line 66:

$element->addDecorator(
                array("outerwrapper" => "HtmlTag"), array("tag" => "div", "class" => "actions")
            );

and it seemed to fix it :)

**Comment by sebastianhoitz** [comment]
This is not an easy to fix issue.

The problem with your suggested solution is, that when you have more than one button in the form, it will look like this:

![problem](http://dl.dropbox.com/u/5912/Jing/2011-12-22_1438.png)

**Comment by professor-monkfish** [comment]
I wonder if a DisplayGroup would help, add all the buttons to a display group, style the group to have "class" => "actions"

**Comment by sebastianhoitz** [comment]
Yes, thats what I was thinking, too. I fixed it now. I'll push my changes in a minute.

**Comment by professor-monkfish** [comment]
Just grabbed this version and tested it and it works really nicely :)))))
