### ISSUE TITLE
Form field size css class

### ISSUE THREAD

**Issue by professor-monkfish** [komola/Bootstrap-Zend-Framework#3]
Each form field should have one of the following css classes:

small
medium
large
xlarge
xxlarge

or a span1 - span16

Do you think the medium class should be added by default? Or maybe the documentation should talk about these classes a little?

**Comment by sebastianhoitz** [comment]
I don't think we should set a default for the form elements.

But you can simply do this on a field in your form:

```
$element->setAttrib("class", "xxlarge");
```

This should work as expected.
