### ISSUE TITLE
Forms with FILE

### ISSUE THREAD

**Issue by professor-monkfish** [komola/Bootstrap-Zend-Framework#4]
This works:

``` php

<?php
class Teon_Form_YouTube extends Zend_Form {

    public function init() {
        $this->addElement('file', 'file', array(
            'required'      => true
        ));
```

This breaks with error 'Warning: Exception caught by form: No file decorator found... unable to render file element'

``` php
<?php
class Teon_Form_YouTube extends Twitter_Form {

    public function init() {

        $this->addElement('file', 'file', array(
            'required'      => true
        ));
```

**Comment by professor-monkfish** [comment]
PS you rock, I love this little library. Here are some internet heart tokens for you ♥♥♥♥♥♥

**Comment by sebastianhoitz** [comment]
This should fix the problem with the file form elements.

Sorry that it took so long to iron this out!
